#!/usr/bin/env bash
set -euo pipefail

# setup_adsb_tar1090_gps_mobile.sh
#
# Installs/configures:
#   - RTL-SDR blacklist rules
#   - gpsd for USB GPS/GNSS
#   - readsb
#   - tar1090
#   - lighttpd
#   - readsb-gps-updater.service
#
# Usage:
#   ./setup_adsb_tar1090_gps_mobile.sh [gps_device] [readsb_service]
#
# Examples:
#   ./setup_adsb_tar1090_gps_mobile.sh
#   ./setup_adsb_tar1090_gps_mobile.sh /dev/ttyACM0 readsb
#
# Environment overrides:
#   FALLBACK_LAT=42.6709
#   FALLBACK_LON=-83.0330
#   MIN_MOVE_METERS=250
#   CHECK_INTERVAL_SECONDS=10
#   MAX_RANGE=450

GPS_DEVICE="${1:-/dev/ttyACM0}"
READSB_SERVICE="${2:-readsb}"

FALLBACK_LAT="${FALLBACK_LAT:-42.6709}"
FALLBACK_LON="${FALLBACK_LON:--83.0330}"
MIN_MOVE_METERS="${MIN_MOVE_METERS:-250}"
CHECK_INTERVAL_SECONDS="${CHECK_INTERVAL_SECONDS:-10}"
MAX_RANGE="${MAX_RANGE:-450}"

UPDATER_BIN="/usr/local/bin/readsb-gps-updater"
UPDATER_SERVICE="/etc/systemd/system/readsb-gps-updater.service"
LOCATION_FILE="/etc/default/readsb-location"
READSB_DEFAULT="/etc/default/readsb"

if [[ "${EUID}" -eq 0 ]]; then
    SUDO=""
else
    SUDO="sudo"
fi

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "[!] Missing required command: $1"
        exit 1
    fi
}

backup_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        $SUDO cp "$file" "${file}.bak.$(date +%Y%m%d-%H%M%S)"
    fi
}

require_cmd systemctl
require_cmd wget
require_cmd curl

export DEBIAN_FRONTEND=noninteractive

echo "[*] Blacklisting DVB drivers that conflict with RTL-SDR dongles..."
$SUDO tee /etc/modprobe.d/blacklist-rtl-sdr.conf >/dev/null <<'BLACKLIST_EOF'
blacklist dvb_usb_rtl28xxu
blacklist dvb_usb_v2
blacklist dvb_core
blacklist rtl2832
blacklist rtl2832_sdr
blacklist rtl2830
blacklist rtl2838
blacklist rc_core
BLACKLIST_EOF

echo "[*] Configuring gpsd for device: ${GPS_DEVICE}"
backup_file /etc/default/gpsd
$SUDO tee /etc/default/gpsd >/dev/null <<GPSD_EOF
START_DAEMON="true"
USBAUTO="true"
DEVICES="${GPS_DEVICE}"
GPSD_OPTIONS="-n"
GPSD_SOCKET="/var/run/gpsd.sock"
GPSD_EOF

echo "[*] Enabling gpsd..."
$SUDO systemctl enable gpsd || true
$SUDO systemctl restart gpsd || true
$SUDO systemctl enable gpsd.socket || true
$SUDO systemctl restart gpsd.socket || true

echo "[*] Installing readsb..."
$SUDO bash -c "$(wget -q -O - https://raw.githubusercontent.com/wiedehopf/adsb-scripts/master/readsb-install.sh)"

echo "[*] Writing initial readsb location file: ${LOCATION_FILE}"
$SUDO tee "${LOCATION_FILE}" >/dev/null <<LOCATION_EOF
# Auto-generated by setup script.
# readsb-gps-updater will overwrite this after GPS gets a live fix.
RECEIVER_LAT="${FALLBACK_LAT}"
RECEIVER_LON="${FALLBACK_LON}"
LOCATION_EOF

echo "[*] Configuring readsb initial receiver position..."
if [[ -f "${READSB_DEFAULT}" ]]; then
    backup_file "${READSB_DEFAULT}"
    $SUDO sed -i '/^DECODER_OPTIONS=/d' "${READSB_DEFAULT}"
    $SUDO tee -a "${READSB_DEFAULT}" >/dev/null <<READSB_EOF

# CarSDR mobile configuration.
# readsb-gps-updater rewrites this DECODER_OPTIONS line when GPS moves enough.
DECODER_OPTIONS="--lat ${FALLBACK_LAT} --lon ${FALLBACK_LON} --max-range ${MAX_RANGE} --write-json-every 1"
READSB_EOF
else
    echo "[!] ${READSB_DEFAULT} not found after readsb install. The updater can still write location, but readsb config was not patched. Tiny tragedy."
fi

echo "[*] Installing readsb GPS updater: ${UPDATER_BIN}"
$SUDO tee "${UPDATER_BIN}" >/dev/null <<'PY_EOF'
#!/usr/bin/env python3
import math
import os
import re
import subprocess
import tempfile
import time
from pathlib import Path

import gps

READSB_DEFAULT = Path(os.environ.get("READSB_DEFAULT", "/etc/default/readsb"))
LOCATION_FILE = Path(os.environ.get("READSB_LOCATION_FILE", "/etc/default/readsb-location"))
READSB_SERVICE = os.environ.get("READSB_SERVICE", "readsb")
MIN_MOVE_METERS = float(os.environ.get("MIN_MOVE_METERS", "250"))
CHECK_INTERVAL_SECONDS = float(os.environ.get("CHECK_INTERVAL_SECONDS", "10"))
MAX_RANGE = os.environ.get("MAX_RANGE", "450")


def distance_meters(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    radius = 6371000.0
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    d_phi = math.radians(lat2 - lat1)
    d_lambda = math.radians(lon2 - lon1)

    a = (
        math.sin(d_phi / 2.0) ** 2
        + math.cos(phi1) * math.cos(phi2) * math.sin(d_lambda / 2.0) ** 2
    )
    return radius * 2.0 * math.atan2(math.sqrt(a), math.sqrt(1.0 - a))


def write_location_file(lat: float, lon: float) -> None:
    LOCATION_FILE.parent.mkdir(parents=True, exist_ok=True)
    LOCATION_FILE.write_text(
        "# Auto-generated by readsb-gps-updater\n"
        f"RECEIVER_LAT=\"{lat:.7f}\"\n"
        f"RECEIVER_LON=\"{lon:.7f}\"\n"
    )


def make_decoder_options(lat: float, lon: float) -> str:
    return (
        f'DECODER_OPTIONS="--lat {lat:.7f} --lon {lon:.7f} '
        f'--max-range {MAX_RANGE} --write-json-every 1"'
    )


def update_readsb_default(lat: float, lon: float) -> bool:
    if not READSB_DEFAULT.exists():
        print(f"[!] {READSB_DEFAULT} does not exist; cannot patch readsb config")
        return False

    old_text = READSB_DEFAULT.read_text()
    new_line = make_decoder_options(lat, lon)

    if re.search(r"^DECODER_OPTIONS=", old_text, flags=re.MULTILINE):
        new_text = re.sub(r"^DECODER_OPTIONS=.*$", new_line, old_text, flags=re.MULTILINE)
    else:
        new_text = old_text.rstrip() + "\n\n# Managed by readsb-gps-updater\n" + new_line + "\n"

    if new_text == old_text:
        return False

    with tempfile.NamedTemporaryFile("w", delete=False, dir=str(READSB_DEFAULT.parent)) as tmp:
        tmp.write(new_text)
        tmp_path = Path(tmp.name)

    tmp_path.replace(READSB_DEFAULT)
    return True


def restart_readsb() -> None:
    if not READSB_SERVICE:
        print("[*] READSB_SERVICE is empty; not restarting readsb")
        return

    print(f"[*] Restarting {READSB_SERVICE}.service")
    subprocess.run(["systemctl", "restart", READSB_SERVICE], check=False)


def main() -> None:
    session = gps.gps(mode=gps.WATCH_ENABLE)
    last_lat = None
    last_lon = None

    print("[*] readsb GPS updater started")
    print(f"[*] readsb default: {READSB_DEFAULT}")
    print(f"[*] location file: {LOCATION_FILE}")
    print(f"[*] update threshold: {MIN_MOVE_METERS} meters")

    while True:
        try:
            report = session.next()

            if report.get("class") != "TPV":
                continue

            lat = getattr(report, "lat", None)
            lon = getattr(report, "lon", None)
            mode = getattr(report, "mode", None)

            if lat is None or lon is None or mode is None or mode < 2:
                print("[*] Waiting for GPS fix...")
                time.sleep(CHECK_INTERVAL_SECONDS)
                continue

            should_update = False

            if last_lat is None or last_lon is None:
                print("[*] First valid GPS fix found")
                should_update = True
            else:
                moved = distance_meters(last_lat, last_lon, lat, lon)
                if moved >= MIN_MOVE_METERS:
                    print(f"[*] Moved {moved:.1f}m; updating readsb location")
                    should_update = True

            if should_update:
                write_location_file(lat, lon)
                config_changed = update_readsb_default(lat, lon)
                if config_changed:
                    restart_readsb()
                last_lat = lat
                last_lon = lon
                print(f"[+] readsb receiver position: {lat:.7f}, {lon:.7f}")

            time.sleep(CHECK_INTERVAL_SECONDS)

        except StopIteration:
            print("[!] gpsd stream ended; retrying")
            time.sleep(CHECK_INTERVAL_SECONDS)
        except Exception as exc:
            print(f"[!] GPS updater error: {exc}")
            time.sleep(CHECK_INTERVAL_SECONDS)


if __name__ == "__main__":
    main()
PY_EOF

$SUDO chmod +x "${UPDATER_BIN}"

echo "[*] Installing systemd service: ${UPDATER_SERVICE}"
$SUDO tee "${UPDATER_SERVICE}" >/dev/null <<SERVICE_EOF
[Unit]
Description=Update readsb receiver location from GPS
After=gpsd.service gpsd.socket ${READSB_SERVICE}.service
Wants=gpsd.service gpsd.socket ${READSB_SERVICE}.service

[Service]
Type=simple
Environment=READSB_SERVICE=${READSB_SERVICE}
Environment=READSB_DEFAULT=${READSB_DEFAULT}
Environment=READSB_LOCATION_FILE=${LOCATION_FILE}
Environment=MIN_MOVE_METERS=${MIN_MOVE_METERS}
Environment=CHECK_INTERVAL_SECONDS=${CHECK_INTERVAL_SECONDS}
Environment=MAX_RANGE=${MAX_RANGE}
ExecStart=/usr/bin/python3 ${UPDATER_BIN}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
SERVICE_EOF

echo "[*] Installing tar1090..."
$SUDO bash -c "$(wget -q -O - https://github.com/wiedehopf/tar1090/raw/master/install.sh)"

if [[ -f /etc/default/tar1090 ]]; then
    backup_file /etc/default/tar1090
    $SUDO sed -i 's/^#\?TAR1090_CENTER_ON_SITE=.*/TAR1090_CENTER_ON_SITE=yes/' /etc/default/tar1090 || true
    grep -q '^TAR1090_CENTER_ON_SITE=' /etc/default/tar1090 || echo 'TAR1090_CENTER_ON_SITE=yes' | $SUDO tee -a /etc/default/tar1090 >/dev/null
fi

echo "[*] Enabling services..."
$SUDO systemctl daemon-reload
$SUDO systemctl enable --now gpsd || true
$SUDO systemctl enable --now gpsd.socket || true
$SUDO systemctl enable --now readsb || true
$SUDO systemctl enable --now lighttpd || true
$SUDO systemctl enable --now readsb-gps-updater.service || true

echo "[*] Restarting services..."
$SUDO systemctl restart gpsd || true
$SUDO systemctl restart gpsd.socket || true
$SUDO systemctl restart readsb || true
$SUDO systemctl restart lighttpd || true
$SUDO systemctl restart readsb-gps-updater.service || true

echo
echo "[*] SDR quick check:"
if command -v rtl_test >/dev/null 2>&1; then
    timeout 5 rtl_test -t || true
else
    echo "[!] rtl_test not found. rtl-sdr package may not have installed correctly. Naturally."
fi

echo
echo "[*] Status:"
systemctl --no-pager --full status gpsd || true
systemctl --no-pager --full status gpsd.socket || true
systemctl --no-pager --full status readsb || true
systemctl --no-pager --full status lighttpd || true
systemctl --no-pager --full status readsb-gps-updater.service || true

echo
echo "[*] Checking tar1090 locally..."
if curl -fsI http://127.0.0.1/tar1090 >/dev/null; then
    echo "[+] tar1090 is reachable: http://127.0.0.1/tar1090"
else
    echo "[!] tar1090 did not respond cleanly yet. Try: journalctl -u readsb -u lighttpd -f"
fi

echo
echo "[+] Setup complete. Your car is now a local radar tower :)"
echo
echo "Useful checks:"
echo "  cgps -s"
echo "  gpspipe -w -n 5"
echo "  rtl_test -t"
echo "  systemctl status gpsd readsb lighttpd readsb-gps-updater"
echo "  journalctl -u readsb-gps-updater -f"
echo "  curl http://127.0.0.1/tar1090"
echo
echo "Recommended if this is the first RTL-SDR blacklist install:"
echo "  sudo reboot"
