FONT_FAMILY = "DejaVu Sans"

COLORS = {
    "app_bg":         "#111418",
    "top_bar_bg":     "#dfe7eb",
    "top_bar_fg":     "#1d2429",
    "top_bar_active": "#cfd9de",
    "status_bg":      "#0b0d10",
    "status_fg":      "#b8c7d3",

    "status_label":           "#9aa4b2",
    "status_primary_value":   "#1f7cff",
    "status_telemetry_value": "#48d11f",

    "tile_bg":       "#20252b",
    "tile_border":   "#384653",
    "tile_accent":   "#0d6fd8",
    "tile_title":    "#ffffff",
    "tile_subtitle": "#b8c7d3",
    "tile_detail":   "#7f8d99",

    "radio_active_preset_bg":     "#d8e0eb",
    "radio_active_preset_fg":    "#0b0d10",
    "radio_active_preset_border": "#1f7cff",
    "radio_control_accent":       "#1f7cff",
    "radio_bank_button_bg":       "#20252b",
    "radio_bank_button_fg":       "#ffffff",
    "radio_bank_button_active_bg": "#1f7cff",
    "radio_bank_button_active_fg": "#0b0d10",

    "volume_button_bg":          "#20252b",
    "volume_button_fg":          "#ffffff",
    "volume_indicator_active":   "#0d6fd8",
    "volume_indicator_inactive": "#6f7a86",

    "power_bg":     "#c62828",
    "power_active": "#a91f1f",
    "power_fg":     "#ffffff",
}

FONTS = {
    "title":         (FONT_FAMILY, 20, "bold"),
    "back":          (FONT_FAMILY, 16, "bold"),
    "power":         (FONT_FAMILY, 22, "bold"),
    "status":        (FONT_FAMILY, 12),
    "tile_title":    (FONT_FAMILY, 26, "bold"),
    "tile_subtitle": (FONT_FAMILY, 15),
    "tile_detail":   (FONT_FAMILY, 12),
    "volume_button": (FONT_FAMILY, 16, "bold"),
}

MENU_TILE_STYLE = {
    "compact": {
        "main_title_font": (FONT_FAMILY, 19, "bold"),
        "preset_title_font": (FONT_FAMILY, 18, "bold"),
        "default_title_font": (FONT_FAMILY, 17, "bold"),
        "subtitle_font": (FONT_FAMILY, 10),
        "detail_font": (FONT_FAMILY, 9),
        "body_padx": 12,
        "body_pady": 8,
        "accent_height": 4,
        "title_wrap": 180,
        "text_wrap": 220,
        "tile_padx": 6,
        "tile_pady": 6,
    },
    "normal": {
        "main_title_font": FONTS["tile_title"],
        "preset_title_font": FONTS["tile_title"],
        "default_title_font": FONTS["tile_title"],
        "subtitle_font": FONTS["tile_subtitle"],
        "detail_font": FONTS["tile_detail"],
        "body_padx": 22,
        "body_pady": 18,
        "accent_height": 5,
        "title_wrap": 260,
        "text_wrap": 300,
        "tile_padx": 10,
        "tile_pady": 10,
    },
}

RADIO_PANEL_THEME = {
    "colors": {
        "panel_bg": COLORS["app_bg"],
        "tile_bg": COLORS["tile_bg"],
        "tile_border": COLORS["tile_border"],
        "tile_title": COLORS["tile_title"],
        "tile_subtitle": COLORS["tile_subtitle"],
        "tile_detail": COLORS["tile_detail"],
        "primary_value": COLORS["status_primary_value"],
        "telemetry_value": COLORS["status_telemetry_value"],
        "status_bg": COLORS["status_bg"],
        "status_label": COLORS["status_label"],
        "control_accent": COLORS["radio_control_accent"],
        "bank_button_bg": COLORS["radio_bank_button_bg"],
        "bank_button_fg": COLORS["radio_bank_button_fg"],
        "bank_button_active_bg": COLORS["radio_bank_button_active_bg"],
        "bank_button_active_fg": COLORS["radio_bank_button_active_fg"],
        "active_preset_bg": COLORS["radio_active_preset_bg"],
        "active_preset_fg": COLORS["radio_active_preset_fg"],
        "active_preset_border": COLORS["radio_active_preset_border"],
    },
    "layout": {
        "root_column": 0,
        "content_row": 0,
        "status_row": 1,
        "control_column": 0,
        "preset_column": 1,
        "control_left_column": 0,
        "control_right_column": 1,
        "control_column_count": 2,
        "control_row_count": 3,
        "bank_column_count": 3,
        "tile_column": 0,
        "preset_number_row": 0,
        "preset_value_row": 1,
        "preset_detail_row": 2,
        "bank_nav_row": 1,
        "nav_row": 0,
        "bank_previous_column": 0,
        "bank_label_column": 1,
        "bank_next_column": 2,
        "icon_column": 0,
        "text_column": 1,
        "body_row": 0,
        "status_content_row": 0,
        "fill_weight": 1,
        "fixed_weight": 0,
        "zero": 0,
        "zero_padding": (0, 0),
        "border_width": 0,
        "expand": True,
        "fill_sticky": "nsew",
        "horizontal_sticky": "ew",
        "northwest_sticky": "nw",
        "north_sticky": "n",
        "horizontal_fill": "x",
        "both_fill": "both",
        "top_side": "top",
        "left_side": "left",
        "left_anchor": "w",
        "center_anchor": "center",
        "left_justify": "left",
        "interactive_cursor": "hand2",
        "fm_panel_key": "fm_radio",
        "fm_precision": 1,
        "default_precision": 3,
        "poll_interval_ms": 2000,
        "rds_mode_name": "WFM",
        "empty_value": "--",
    },
    "profiles": {
        "compact": {
            "main_column_weights": (3, 2),
            "column_gap": 6,
            "control_tile_pad": 4,
            "preset_tile_pad": 4,
            "tile_border_width": 2,
            "control_accent_height": 4,
            "control_body_padx": 5,
            "control_body_pady": 6,
            "control_icon_font": (FONT_FAMILY, 20, "bold"),
            "control_icon_width": 1,
            "control_icon_gap": 4,
            "control_icon_pady": 1,
            "control_title_font": (FONT_FAMILY, 16, "bold"),
            "control_subtitle_font": (FONT_FAMILY, 10),
            "control_detail_font": (FONT_FAMILY, 8),
            "control_text_wrap": 145,
            "control_subtitle_pady": 4,
            "control_detail_pady": 2,
            "preset_number_font": (FONT_FAMILY, 10, "bold"),
            "preset_frequency_font": (FONT_FAMILY, 17, "bold"),
            "preset_detail_font": (FONT_FAMILY, 8),
            "preset_number_padx": 8,
            "preset_number_pady": 5,
            "preset_value_padx": 6,
            "preset_detail_padx": 6,
            "preset_detail_pady": 5,
            "bank_button_font": (FONT_FAMILY, 8),
            "bank_nav_top_pad": 4,
            "bank_button_padx": 8,
            "bank_button_pady": 3,
            "bank_button_gap": 4,
            "bank_label_padx": 4,
            "status_top_pad": 6,
            "status_ipady": 3,
            "status_group_padx": 4,
            "status_value_gap": 4,
            "status_font": (FONT_FAMILY, 9),
        },
        "normal": {
            "main_column_weights": (3, 2),
            "column_gap": 6,
            "control_tile_pad": 6,
            "preset_tile_pad": 6,
            "tile_border_width": 2,
            "control_accent_height": 4,
            "control_body_padx": 14,
            "control_body_pady": 10,
            "control_icon_font": (FONT_FAMILY, 28, "bold"),
            "control_icon_width": 2,
            "control_icon_gap": 12,
            "control_icon_pady": 2,
            "control_title_font": (FONT_FAMILY, 24, "bold"),
            "control_subtitle_font": (FONT_FAMILY, 14),
            "control_detail_font": (FONT_FAMILY, 11),
            "control_text_wrap": 260,
            "control_subtitle_pady": 7,
            "control_detail_pady": 3,
            "preset_number_font": (FONT_FAMILY, 13, "bold"),
            "preset_frequency_font": (FONT_FAMILY, 24, "bold"),
            "preset_detail_font": (FONT_FAMILY, 13),
            "preset_number_padx": 10,
            "preset_number_pady": 7,
            "preset_value_padx": 8,
            "preset_detail_padx": 8,
            "preset_detail_pady": 9,
            "bank_button_font": FONTS["status"],
            "bank_nav_top_pad": 4,
            "bank_button_padx": 8,
            "bank_button_pady": 3,
            "bank_button_gap": 4,
            "bank_label_padx": 4,
            "status_top_pad": 6,
            "status_ipady": 3,
            "status_group_padx": 4,
            "status_value_gap": 4,
            "status_font": FONTS["status"],
        },
    },
}


CAR_UI_THEME = {
    "colors": {
        "app_bg": COLORS["app_bg"],
        "status_bg": COLORS["status_bg"],
        "status_fg": COLORS["status_fg"],
        "tile_bg": COLORS["tile_bg"],
        "tile_border": COLORS["tile_border"],
        "tile_accent": COLORS["tile_accent"],
        "tile_title": COLORS["tile_title"],
        "tile_subtitle": COLORS["tile_subtitle"],
        "tile_detail": COLORS["tile_detail"],
    },
    "window": {
        "minimum_size": (800, 480),
        "default_profile": "vm",
        "default_geometry": "1024x600",
        "compact_max_width": 900,
        "compact_max_height": 520,
        "fullscreen_env": "CARUI_FULLSCREEN",
        "geometry_env": "CARUI_GEOMETRY",
        "profile_env": "CARUI_DISPLAY_PROFILE",
        "profiles": {
            "legacy": "800x480",
            "compact": "800x480",
            "vm": "1024x600",
            "desktop": "1024x600",
            "touch2": "1280x720",
            "display2": "1280x720",
            "rpi-touch2": "1280x720",
        },
    },
    "layout": {
        "dashboard_columns": 3,
        "dashboard_rows": 2,
        "fill_weight": 1,
        "tile_border_width": 2,
        "tile_border": 0,
        "tile_cursor": "hand2",
        "fill_both": "both",
        "fill_horizontal": "x",
        "side_top": "top",
        "side_bottom": "bottom",
        "anchor_left": "w",
        "anchor_center": "center",
        "justify_left": "left",
        "justify_center": "center",
        "sticky_fill": "nsew",
        "empty_value": "--",
        "gps_poll_interval_ms": 1000,
        "volume_steps": 8,
    },
    "profiles": {
        "compact": {
            "content_padx": 8,
            "content_pady": 8,
            "status_font": (FONT_FAMILY, 9),
            "status_padx": 10,
            "status_pady": 4,
            "tile_grid_padx": 6,
            "tile_grid_pady": 6,
            "main_title_font": MENU_TILE_STYLE["compact"]["main_title_font"],
            "preset_title_font": MENU_TILE_STYLE["compact"]["preset_title_font"],
            "default_title_font": MENU_TILE_STYLE["compact"]["default_title_font"],
            "subtitle_font": MENU_TILE_STYLE["compact"]["subtitle_font"],
            "detail_font": MENU_TILE_STYLE["compact"]["detail_font"],
            "body_padx": MENU_TILE_STYLE["compact"]["body_padx"],
            "body_pady": MENU_TILE_STYLE["compact"]["body_pady"],
            "accent_height": MENU_TILE_STYLE["compact"]["accent_height"],
            "title_wrap": MENU_TILE_STYLE["compact"]["title_wrap"],
            "text_wrap": MENU_TILE_STYLE["compact"]["text_wrap"],
            "subtitle_top_pad": 3,
            "detail_top_pad": 2,
        },
        "normal": {
            "content_padx": 18,
            "content_pady": 18,
            "status_font": FONTS["status"],
            "status_padx": 14,
            "status_pady": 10,
            "tile_grid_padx": 10,
            "tile_grid_pady": 10,
            "main_title_font": MENU_TILE_STYLE["normal"]["main_title_font"],
            "preset_title_font": MENU_TILE_STYLE["normal"]["preset_title_font"],
            "default_title_font": MENU_TILE_STYLE["normal"]["default_title_font"],
            "subtitle_font": MENU_TILE_STYLE["normal"]["subtitle_font"],
            "detail_font": MENU_TILE_STYLE["normal"]["detail_font"],
            "body_padx": MENU_TILE_STYLE["normal"]["body_padx"],
            "body_pady": MENU_TILE_STYLE["normal"]["body_pady"],
            "accent_height": MENU_TILE_STYLE["normal"]["accent_height"],
            "title_wrap": MENU_TILE_STYLE["normal"]["title_wrap"],
            "text_wrap": MENU_TILE_STYLE["normal"]["text_wrap"],
            "subtitle_top_pad": 3,
            "detail_top_pad": 2,
        },
    },
}
TOP_BAR_THEME = {
    "colors": {
        "background": COLORS["top_bar_bg"],
        "foreground": COLORS["top_bar_fg"],
        "active": COLORS["top_bar_active"],
        "volume_button_bg": COLORS["volume_button_bg"],
        "volume_button_fg": COLORS["volume_button_fg"],
        "volume_indicator_active": COLORS["volume_indicator_active"],
        "volume_indicator_inactive": COLORS["volume_indicator_inactive"],
        "power_bg": COLORS["power_bg"],
        "power_fg": COLORS["power_fg"],
        "power_active": COLORS["power_active"],
    },
    "layout": {
        "column_count": 3,
        "column_weight": 1,
        "row": 0,
        "left_column": 0,
        "center_column": 1,
        "right_column": 2,
        "left_sticky": "w",
        "fill_sticky": "nsew",
        "right_sticky": "e",
        "left_side": "left",
        "right_side": "right",
        "center_anchor": "center",
        "bottom_anchor": "s",
        "cursor": "hand2",
        "zero": 0,
        "back_button_text": "‹",
        "volume_down_text": "−",
        "volume_up_text": "+",
        "settings_text": "⚙",
        "power_text": "⏻",
        "empty_frequency": "--",
        "empty_location": "🌎 lat.--, lon.--",
        "button_border_width": 0,
        "back_border_width": 1,
        "button_height": 1,
    },
    "profiles": {
        "compact": {
            "height": 50,
            "default_title": "Drive UbiquitOS",
            "group_pady": 6,
            "left_padx": 8,
            "right_padx": 10,
            "back_font": (FONT_FAMILY, 12, "bold"),
            "back_padx": 10,
            "back_pady": 4,
            "back_button_gap": 8,
            "title_font": (FONT_FAMILY, 16, "bold"),
            "frequency_font": (FONT_FAMILY, 13, "bold"),
            "location_font": (FONT_FAMILY, 9),
            "location_padx": 6,
            "location_gap": 8,
            "volume_button_font": FONTS["volume_button"],
            "volume_button_width": 3,
            "volume_button_gap": 4,
            "volume_bar_width": 5,
            "volume_bar_base_height": 8,
            "volume_bar_height_step": 2,
            "volume_bar_gap": 1,
            "indicator_left_gap": 4,
            "indicator_right_gap": 6,
            "settings_font": (FONT_FAMILY, 13, "bold"),
            "power_font": (FONT_FAMILY, 14, "bold"),
            "control_button_width": 3,
            "settings_gap": 8,
        },
        "normal": {
            "height": 68,
            "default_title": "Drive UbiquitOS Control Panel",
            "group_pady": 8,
            "left_padx": 8,
            "right_padx": 16,
            "back_font": FONTS["back"],
            "back_padx": 16,
            "back_pady": 6,
            "back_button_gap": 12,
            "title_font": FONTS["title"],
            "frequency_font": (FONT_FAMILY, 18, "bold"),
            "location_font": FONTS["status"],
            "location_padx": 10,
            "location_gap": 12,
            "volume_button_font": FONTS["volume_button"],
            "volume_button_width": 3,
            "volume_button_gap": 4,
            "volume_bar_width": 5,
            "volume_bar_base_height": 8,
            "volume_bar_height_step": 2,
            "volume_bar_gap": 1,
            "indicator_left_gap": 4,
            "indicator_right_gap": 6,
            "settings_font": (FONT_FAMILY, 17, "bold"),
            "power_font": (FONT_FAMILY, 18, "bold"),
            "control_button_width": 4,
            "settings_gap": 8,
        },
    },
    "compact_titles": {
        "NOAA Weather Radio": "NOAA WX",
        "FM Broadcast Radio": "FM Radio",
        "Airband AM Radio": "Airband",
        "Ham Radio": "HAM",
    },
}

STATUS_BAR_THEME = {
    "colors": {
        "background": COLORS["status_bg"],
        "foreground": COLORS["status_fg"],
    },
    "layout": {
        "anchor": "w",
        "fill": "x",
        "side": "bottom",
    },
    "profiles": {
        "compact": {
            "font": (FONT_FAMILY, 9),
            "padx": 10,
            "pady": 4,
        },
        "normal": {
            "font": FONTS["status"],
            "padx": 14,
            "pady": 10,
        },
    },
}
